### ISSUE TITLE
it does not work

### ISSUE THREAD

**Issue by madrid2022ok** [angjelkom/flutter_netflix#2]
![04469FE8-2959-4681-B430-E6F0B9816AFF](https://user-images.githubusercontent.com/105641464/215269533-cb0d41f0-945d-4c9e-9d6a-125c1456f9e6.jpeg)
![8D542335-3730-4A58-862E-42E43EC63261](https://user-images.githubusercontent.com/105641464/215269536-367f634f-a5f7-433b-ad5d-a9bd85050616.jpeg)

no play video I can't download the categories doesn't work

**Comment by thomastthai** [comment]
The app is a demo of the UI and RESTful data pull and not a full-blown Netflix app. Not all links and buttons will work.

**Comment by angjelkom** [comment]
@madrid2022ok as @thomastthai pointed out, this is a Demo UI Clone, showcasing the Flutter capabilities, its purpose is not to provide an open-source Netflix alternative.
